modLoader="javafml" #mandatory

loaderVersion="[35,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.

license="All rights reserved"

issueTrackerURL="http://my.issue.tracker/" #optional

[[mods]] #mandatory

modId="firenblood" #mandatory

version="1.16.4 - 1.1.0" #mandatory

displayName="Fire N' Blood" #mandatory

updateJSONURL="http://myurl.me/" #optional

displayURL="https://github.com/Polarice3/FireNBlood" #optional

logoFile="Logo.png" #optional

credits="Special thanks to Technovision and TelepathicGrunt for their tutorials and diesieben07 for helping me with a problem!

Credit to Alex666 for event codes, and Ipsis for certain codes!" #optional

authors="anogon" #optional

description='''
My first Mod
'''

[[dependencies.firenblood]] #optional

    modId="forge" #mandatory

    mandatory=true #mandatory

    versionRange="[35,)" #mandatory

    ordering="NONE"

    side="BOTH"

[[dependencies.firenblood]]
    modId="minecraft"
    mandatory=true

    versionRange="[1.16.4,1.17)"
    ordering="NONE"
    side="BOTH"
