modLoader="javafml" #mandatory

loaderVersion="[35,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.

license="All rights reserved"

issueTrackerURL="https://github.com/Polarice3/FireNBlood/issues" #optional

[[mods]] #mandatory

modId="firenblood" #mandatory

version="1.16.5 - 1.6.0" #mandatory

displayName="Fire N' Blood" #mandatory

updateJSONURL="http://myurl.me/" #optional

displayURL="https://github.com/Polarice3/FireNBlood" #optional

logoFile="fnblogo.png" #optional

credits="Special thanks to Technovision, Cy4's Modding and TelepathicGrunt for their tutorials and diesieben07 for helping me with a problem!

Credit to Alex666 for event, spawner and config codes, hollingsworth for Vex codes,
baileyholl for HUD codes, Lothrazar for Teleporting codes,
vemerion and MrCrayfish for wand and staff inventory codes and Ipsis for certain codes!" #optional

authors="anogon" #optional

description='''
Fire N' Blood adds a bunch of new Mobs that can help or hinder players and a magic system that can provides a player a different way of combat!
'''

[[dependencies.firenblood]] #optional

    modId="forge" #mandatory

    mandatory=true #mandatory

    versionRange="[35,)" #mandatory

    ordering="NONE"

    side="BOTH"

[[dependencies.firenblood]]
    modId="minecraft"
    mandatory=true

    versionRange="[1.16.4,1.17)"
    ordering="NONE"
    side="BOTH"
